function organize_outputs(out_dir,roiinfo_csv)

% PDF
system(['cd ' out_dir ' && mkdir PDF && mv fsthalconnMNI.pdf PDF']);


% Unsmoothed connmaps
system(['cd ' out_dir ' && ' ...
	' mkdir ZMAPS_KEEPGM_NATIVE && ' ...
	' mv connmaps/Z_*_keepgm.nii ZMAPS_KEEPGM_NATIVE && ' ...
	' gzip ZMAPS_KEEPGM_NATIVE/*.nii']);

system(['cd ' out_dir ' && ' ...
	' mkdir ZMAPS_REMOVEGM_NATIVE && ' ...
	' mv connmaps/Z_*_removegm.nii ZMAPS_REMOVEGM_NATIVE && ' ...
	' gzip ZMAPS_REMOVEGM_NATIVE/*.nii']);

system(['cd ' out_dir ' && ' ...
	' mkdir ZMAPS_KEEPGM_MNI && ' ...
	' mv connmaps/Z_*_wkeepgm.nii ZMAPS_KEEPGM_MNI && ' ...
	' gzip ZMAPS_KEEPGM_MNI/*.nii']);

system(['cd ' out_dir ' && ' ...
	' mkdir ZMAPS_REMOVEGM_MNI && ' ...
	' mv connmaps/Z_*_wremovegm.nii ZMAPS_REMOVEGM_MNI && ' ...
	' gzip ZMAPS_REMOVEGM_MNI/*.nii']);


% Smoothed connmaps
system(['cd ' out_dir ' && ' ...
	' mkdir SZMAPS_KEEPGM_NATIVE && ' ...
	' mv connmaps/sZ_*_keepgm.nii SZMAPS_KEEPGM_NATIVE && ' ...
	' gzip SZMAPS_KEEPGM_NATIVE/*.nii']);

system(['cd ' out_dir ' && ' ...
	' mkdir SZMAPS_REMOVEGM_NATIVE && ' ...
	' mv connmaps/sZ_*_removegm.nii SZMAPS_REMOVEGM_NATIVE && ' ...
	' gzip SZMAPS_REMOVEGM_NATIVE/*.nii']);

system(['cd ' out_dir ' && ' ...
	' mkdir SZMAPS_KEEPGM_MNI && ' ...
	' mv connmaps/sZ_*_wkeepgm.nii SZMAPS_KEEPGM_MNI && ' ...
	' gzip SZMAPS_KEEPGM_MNI/*.nii']);

system(['cd ' out_dir ' && ' ...
	' mkdir SZMAPS_REMOVEGM_MNI && ' ...
	' mv connmaps/sZ_*_wremovegm.nii SZMAPS_REMOVEGM_MNI && ' ...
	' gzip SZMAPS_REMOVEGM_MNI/*.nii']);


% Conn matrix
system(['cd ' out_dir ' && mkdir RMATRIX && mv R_*.csv RMATRIX']);
system(['cd ' out_dir ' && mkdir ZMATRIX && mv Z_*.csv ZMATRIX']);


% ROI images
system(['cd ' out_dir ' && mkdir ROIS && mv subject_rois/roi_*.nii ROIS && ' ...
	'gzip ROIS/*.nii']);


% Extracted ROI time series
system(['cd ' out_dir ' && mkdir ROIDATA && mv roidata_*.csv ROIDATA']);


% ROI spec
system(['cd ' out_dir ' && mkdir ROISPEC && ' ...
	' cp ' which(roiinfo_csv) ' ROISPEC']);


