function test_pdf(src_path,magick_path,fsl_path,out_dir,project,subject,session,scan)

%% Libraries
system([ ...
	'export LD_LIBRARY_PATH= && ' ...
	'export FREESURFER_HOME=/usr/local/freesurfer && ' ...
	'. $FREESURFER_HOME/SetUpFreeSurfer.sh && ' ...
	'ldd /usr/local/freesurfer/bin/freeview && ' ...
	'env ' ...
	]);


%% freeview screenshots
system([ ...
	'LD_LIBRARY_PATH= ' ...
	'PATH=' src_path ':' magick_path ':' fsl_path ':$PATH ' ...
	'OUT=' out_dir ' ' ...
	'project=' project ' ' ...
	'subject=' subject ' ' ...
	'session=' session ' ' ...
	'scan=' scan ' ' ...
	'screenshots.sh' ...
	'< /dev/null' ...
	]);


%% Combine images to PDF
system( [ ...
	'cd ' out_dir ' && ' ...
	magick_path '/convert ' ...
	'connmatrix.png ' ...
	'coreg.png ' ...
	'wkdir/page_rois_cort.png ' ...
	'wkdir/page_rois_thal.png ' ...
	'wkdir/page_rois_fs.png ' ...
	'wkdir/page_conn_mni.png ' ...
	'fsthalconnMNI.pdf' ...
	'< /dev/null' ...
	] );

